version: '3.8'

services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # railsからアクセスするときに必要
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    # ホスト側のディレクトリをコンテナで使用する
    volumes:
      - ./tmp/db:/var/lib/mysql
      # - ./api/tmp/db:/var/lib/mysql

  api:
    # ベースイメージとなるDockerfileを指定
    build:
      # Dockerfileパスを指定
      context: .
      # Dockerfileに変数を渡す
      # args:
      #   WORKDIR: $WORKDIR
    environment:
      MYSQL_ROOT_PASSWORD: password
    # api直下の全てのファイルをコンテナに使用する
    # ホスト側の変更がリアルタイムでコンテナに反映される
    volumes:
      - .:/app
      # - ./api:/$WORKDIR

    # apiサービス起動前にdbサービスを起動する設定
    depends_on:
      - db
    # 公開用ポート番号
    # 公開したいポート番号：コンテナポート
    ports:
      - "3000:3000"

  # front:
  #   build:
  #     context: ./front
  #     args:
  #       WORKDIR: $WORKDIR
  #   # コンテナで実行したいコマンド
  #   # 開発環境用のコマンド
  #   command: yarn run dev
  #   volumes:
  #     - ./front:/$WORKDIR
  #   ports:
  #     - "8080:3000"
  #   depends_on:
  #     - api