name: Run RSpec

on:
  push:

jobs:
  rspec:
    name: RSpec Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.31
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: Set up Node.js (for Rails assets)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Database setup and migrate
        run: |
          cd api
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run rspec
        run: |
          cd api
          bundle exec rspec